source "http://rubygems.org"
gem "fakeweb",       "~> 1.3.0"
gem "cucumber",      "~> 0.10.6"
gem "activesupport", "~> 2.3.8"
gem "activerecord",  "~> 2.3.8"
gem "actionpack",    "~> 2.3.8"
gem "nokogiri",      "~> 1.4.3.1"
gem "shoulda",       "~> 2.11.3"
gem 'bourne',        '>= 1.0'
gem "sham_rack",     "~> 1.3.0"
